# Puerto y cookie
server:
  port: 9003
  reactive:
    session:
      cookie:
        name: GT_SESSION
        path: /
        same-site: None      # antes lax (minucula)
        secure: true       # true para prod, la cookie solo ira cifrada bajo HTTPS
        http-only: true

spring:
# Rutas Gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-recado
              # uri: http://localhost:9011
              predicates:
                - Path=/api/ms-recado/v1/**
              uri: http://ms-recado-svc:9011
              filters:
                - TokenRelay
                - StripPrefix=3
            - id: fe-recado
              predicates:
                - Path=/fe-recado/**
              uri: http://fe-recado-svc:4200
              filters:
                - StripPrefix=1
# Oauth2 Client
  security:
    oauth2:
      client:
        registration:
          mi-gateway:
            client-id: migateway
            client-secret: migate
            scope: openid, profile
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          mi-gateway:
            # issuer-uri: "http://localhost:9000"
            issuer-uri: "http://auth-server-svc:9000"

# Logs
logging:
  level:
    org:
      springframework:
        security: TRACE
    com:
      jarones:
        ms_recado: DEBUG